version: '3.8'

services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: personal-assistant
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=postgres
      - DB_NAME=personal_assistant
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: personal_assistant
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
